# Generated by Django 5.0.6 on 2024-06-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0002_category_slug_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
