# Generated by Django 5.0.6 on 2024-06-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0003_alter_category_slug_alter_event_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
    ]
